# Generated by Django 5.2.2 on 2026-06-09 23:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('website', models.URLField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='')),
                ('price_level', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'places',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['city', 'category'], name='places_city_a0be57_idx'), models.Index(fields=['is_active'], name='places_is_acti_520eb0_idx')],
            },
        ),
    ]
