# Generated by Django 5.2.2 on 2026-06-09 23:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('activity_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('bar', 'Bar'), ('cinema', 'Cinema'), ('museum', 'Museum'), ('park', 'Park'), ('sports', 'Sports'), ('concert', 'Concert'), ('gaming', 'Gaming'), ('tourism', 'Tourism'), ('shopping', 'Shopping')], db_index=True, max_length=50)),
                ('min_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_people', models.PositiveSmallIntegerField(default=1)),
                ('max_people', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('indoor', models.BooleanField(default=False)),
                ('outdoor', models.BooleanField(default=False)),
                ('score_base', models.PositiveSmallIntegerField(default=50)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='places.place')),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['-score_base', 'name'],
                'indexes': [models.Index(fields=['activity_type', 'is_active'], name='activities_activit_f0bfe3_idx'), models.Index(fields=['indoor', 'outdoor'], name='activities_indoor_8b887f_idx')],
            },
        ),
    ]
